### ISSUE TITLE
Strict checking of sum(init) != 1 can be false in R and true in C++

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimbleEcology#18]
In dHMM and other distributions, there is a check of whether `sum(init) != 1`, with an error if true.

Even if the `init` vector satisfies `sum(init) == 1` in R, this condition can be false in C++, presumably due to floating point arithmetic issues, with possibly different orders in R vs C++ or something like that.

In such a case, which was reported by a user, it can be hard to work around.  One can normalize the vector in R and still have `sum(init) != 1` in C++.

How about replacing this condition with something like `abs(sum(init) - 1) < 1e-6` or perhaps a stricter tolerance? This is similar to the other checks in nearby code that allow some numerical imprecision.

**Comment by dochvam** [comment]
This is fixed as of nimbleEcology 0.4.0
